### ISSUE TITLE
exist called before definition

### ISSUE THREAD

**Issue by CtlAltDel6** [SebastianObi/RNS-Tools#2]
May be a problem with my setup, running python script from /home/user and have the .mu file in ~/.nomadnetwork/storage/pages
On run i get exist called before defined error everytime it catches a new announce

**Comment by SebastianObi** [comment]
In the future it would be helpful to get more information about which files are used etc. I assume that it is the 'rns_announce_directory'.

I have fixed various errors. It should work now.

Update the following files:
[rns_announce_directory.py](https://github.com/SebastianObi/RNS-Tools/blob/main/rns_announce_directory/rns_announce_directory.py)
[rns_announce_directory.mu](https://github.com/SebastianObi/RNS-Tools/blob/main/rns_announce_directory/rns_announce_directory.mu)

The 'rns_announce_directory.mu' file is just an example. You have to adapt it to your own needs.
